<Project>
	<PropertyGroup>
		<NoWarn>CS8632;RS0016</NoWarn>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<DefineConstants>JETBRAINS_ANNOTATIONS</DefineConstants>
		<LangVersion>preview</LangVersion>
		<Features>InterceptorsPreview</Features>
		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Logging.AutoLoggerMessage</InterceptorsNamespaces>
	</PropertyGroup>
	<PropertyGroup Condition="!$(MSBuildProjectName.EndsWith('Tests'))">
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage"/>
	</ItemGroup>
</Project>