// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY
using VkNet.Model.RequestParams;
using VkNet.Model.RequestParams.Database;

// ReSharper disable MissingAnnotation

namespace VkNet.Utils
{
	partial class VkParameters
	{
		/// <summary>
		/// Преобразование класса <see cref="AccountRegisterDeviceParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AccountRegisterDeviceParams p)
		{
			return AccountRegisterDeviceParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(SearchGetHintsParams p)
		{
			return SearchGetHintsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PostAdsStealthParams p)
		{
			return PostAdsStealthParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(EditAdsStealthParams p)
		{
			return EditAdsStealthParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoGetCatalogParams p)
		{
			return VideoGetCatalogParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(LinkStatsParams p)
		{
			return LinkStatsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesSearchParams p)
		{
			return MessagesSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GetCitiesParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(CallbackServerParams p)
		{
			return CallbackServerParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GetCitiesParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessageEditParams p)
		{
			return MessageEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GetCitiesParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GetCitiesParams p)
		{
			return GetCitiesParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AccountSaveProfileInfoParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AccountSaveProfileInfoParams p)
		{
			return AccountSaveProfileInfoParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AppGetCatalogParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AppGetCatalogParams p)
		{
			return AppGetCatalogParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AppGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AppGetParams p)
		{
			return AppGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AppSendRequestParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AppSendRequestParams p)
		{
			return AppSendRequestParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AudioEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AudioEditParams p)
		{
			return AudioEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AudioGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AudioGetParams p)
		{
			return AudioGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AudioSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AudioSearchParams p)
		{
			return AudioSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AuthConfirmParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AuthConfirmParams p)
		{
			return AuthConfirmParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AuthSignupParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AuthSignupParams p)
		{
			return AuthSignupParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardAddTopicParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardAddTopicParams p)
		{
			return BoardAddTopicParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardCommentParams p)
		{
			return BoardCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardCreateCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardCreateCommentParams p)
		{
			return BoardCreateCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardEditCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardEditCommentParams p)
		{
			return BoardEditCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardEditTopicParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardEditTopicParams p)
		{
			return BoardEditTopicParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardGetCommentsParams p)
		{
			return BoardGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardGetTopicsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardGetTopicsParams p)
		{
			return BoardGetTopicsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="BoardTopicParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(BoardTopicParams p)
		{
			return BoardTopicParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="FriendsGetMutualParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(FriendsGetMutualParams p)
		{
			return FriendsGetMutualParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="FriendsGetOnlineParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(FriendsGetOnlineParams p)
		{
			return FriendsGetOnlineParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="FriendsGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(FriendsGetParams p)
		{
			return FriendsGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="FriendsGetRequestsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(FriendsGetRequestsParams p)
		{
			return FriendsGetRequestsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="FriendsSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(FriendsSearchParams p)
		{
			return FriendsSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsBanUserParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsBanUserParams p)
		{
			return GroupsBanUserParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsEditManagerParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsEditManagerParams p)
		{
			return GroupsEditManagerParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsEditParams p)
		{
			return GroupsEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsGetMembersParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsGetMembersParams p)
		{
			return GroupsGetMembersParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsGetParams p)
		{
			return GroupsGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="GroupsSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(GroupsSearchParams p)
		{
			return GroupsSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="LikesAddParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(LikesAddParams p)
		{
			return LikesAddParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="LikesGetListParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(LikesGetListParams p)
		{
			return LikesGetListParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MarketCreateCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MarketCreateCommentParams p)
		{
			return MarketCreateCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MarketGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MarketGetCommentsParams p)
		{
			return MarketGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MarketProductParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MarketProductParams p)
		{
			return MarketProductParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MarketSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MarketSearchParams p)
		{
			return MarketSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesDialogsGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesDialogsGetParams p)
		{
			return MessagesDialogsGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesGetHistoryAttachmentsParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesGetHistoryAttachmentsParams p)
		{
			return MessagesGetHistoryAttachmentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesGetHistoryParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesGetHistoryParams p)
		{
			return MessagesGetHistoryParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesGetLongPollHistoryParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesGetLongPollHistoryParams p)
		{
			return MessagesGetLongPollHistoryParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesGetParams p)
		{
			return MessagesGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesSendParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesSendParams p)
		{
			return MessagesSendParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="MessagesSendStickerParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(MessagesSendStickerParams p)
		{
			return MessagesSendStickerParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="NewsFeedGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(NewsFeedGetCommentsParams p)
		{
			return NewsFeedGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="NewsFeedGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(NewsFeedGetParams p)
		{
			return NewsFeedGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="NewsFeedGetRecommendedParams" /> в
		/// VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(NewsFeedGetRecommendedParams p)
		{
			return NewsFeedGetRecommendedParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="NewsFeedSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(NewsFeedSearchParams p)
		{
			return NewsFeedSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PagesGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PagesGetParams p)
		{
			return PagesGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoCreateAlbumParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoCreateAlbumParams p)
		{
			return PhotoCreateAlbumParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoCreateCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoCreateCommentParams p)
		{
			return PhotoCreateCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoEditAlbumParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoEditAlbumParams p)
		{
			return PhotoEditAlbumParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoEditParams p)
		{
			return PhotoEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetAlbumsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetAlbumsParams p)
		{
			return PhotoGetAlbumsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetAllCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetAllCommentsParams p)
		{
			return PhotoGetAllCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetAllParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetAllParams p)
		{
			return PhotoGetAllParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetCommentsParams p)
		{
			return PhotoGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetParams p)
		{
			return PhotoGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoGetUserPhotosParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoGetUserPhotosParams p)
		{
			return PhotoGetUserPhotosParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoPutTagParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoPutTagParams p)
		{
			return PhotoPutTagParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoSaveParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoSaveParams p)
		{
			return PhotoSaveParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PhotoSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PhotoSearchParams p)
		{
			return PhotoSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsAddVoteParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsAddVoteParams p)
		{
			return PollsAddVoteParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsCreateParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsCreateParams p)
		{
			return PollsCreateParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsDeleteVoteParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsDeleteVoteParams p)
		{
			return PollsDeleteVoteParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsEditParams p)
		{
			return PollsEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsGetByIdParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsGetByIdParams p)
		{
			return PollsGetByIdParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="PollsGetVotersParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(PollsGetVotersParams p)
		{
			return PollsGetVotersParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="UserSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(UserSearchParams p)
		{
			return UserSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="UsersGetNearbyParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(UsersGetNearbyParams p)
		{
			return UsersGetNearbyParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoCreateCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoCreateCommentParams p)
		{
			return VideoCreateCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoEditParams p)
		{
			return VideoEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoGetCommentsParams p)
		{
			return VideoGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoGetParams p)
		{
			return VideoGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoReorderVideosParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoReorderVideosParams p)
		{
			return VideoReorderVideosParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoSaveParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoSaveParams p)
		{
			return VideoSaveParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="VideoSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(VideoSearchParams p)
		{
			return VideoSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallAddCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallAddCommentParams p)
		{
			return WallAddCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallCreateCommentParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallCreateCommentParams p)
		{
			return WallCreateCommentParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallEditParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallEditParams p)
		{
			return WallEditParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallGetCommentsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallGetCommentsParams p)
		{
			return WallGetCommentsParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallGetParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallGetParams p)
		{
			return WallGetParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallPostParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallPostParams p)
		{
			return WallPostParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="WallSearchParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(WallSearchParams p)
		{
			return WallSearchParams.ToVkParameters(p: p);
		}

		/// <summary>
		/// Преобразование класса <see cref="AdsGetCampaignsParams" /> в VkParameters
		/// </summary>
		/// <param name="p"> Параметр. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkParameters(AdsGetCampaignsParams p)
		{
			return AdsGetCampaignsParams.ToVkParameters(p: p);
		}
	}
}