// Autogenerated at 08.12.2015 10:51:53
// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY

using VkNet.Model.RequestParams;

namespace VkNet.Utils
{
    using System.Collections.Generic;

    partial class VkParameters : Dictionary<string, string>
    {
		public static implicit operator VkParameters(AccountSaveInfoParams p)
		{
            return AccountSaveInfoParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(AudioSearchParams p)
		{
            return AudioSearchParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(DialogsGetParams p)
		{
            return DialogsGetParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(GetLongPollHistoryParams p)
		{
            return GetLongPollHistoryParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(HistoryGetParams p)
		{
            return HistoryGetParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(MessageSendParams p)
		{
            return MessageSendParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(MessagesGetParams p)
		{
            return MessagesGetParams.ToVkParameters(p);
        }
		public static implicit operator VkParameters(WallGetParams p)
		{
            return WallGetParams.ToVkParameters(p);
        }

	}
}