// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY

using VkNet.Model;
using VkNet.Model.Attachments;
using VkNet.Model.RequestParams;
using VkNet.UWP.Model.Attachments;

namespace VkNet.Utils
{
	public partial class VkResponse
	{
		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MessagesSendResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: MessagesSendResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PageVersion(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: PageVersion.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator FriendsDeleteResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: FriendsDeleteResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AreFriendsResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: AreFriendsResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator CallbackSettings(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: CallbackSettings.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator CallbackServerItem(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: CallbackServerItem.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ChatPreviewField(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: ChatPreviewField.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ChatPreview(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: ChatPreview.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ChatPhoto(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: ChatPhoto.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Email(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: Email.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AccountInfo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : AccountInfo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AccountPushSettings(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: AccountPushSettings.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ShortLink(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : ShortLink.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AccountChangePasswordResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: AccountChangePasswordResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Album(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Album.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator App(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : App.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AppGetObject(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : AppGetObject.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Application(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Application.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ApplicationContent(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: ApplicationContent.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Attachment(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Attachment.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Audio(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Audio.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AudioAlbum(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : AudioAlbum.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AuthConfirmResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : AuthConfirmResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator BanInfo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : BanInfo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Button(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Button.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Career(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Career.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator CategoryGroup(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : CategoryGroup.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Chair(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Chair.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ChangeNameRequest(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : ChangeNameRequest.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Chat(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Chat.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ChatPushSettings(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : ChatPushSettings.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator City(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : City.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Comment(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Comment.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Comments(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Comments.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Connections(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Connections.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Contact(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Contact.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Contacts(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Contacts.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Counters(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Counters.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Country(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Country.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator CropPhoto(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : CropPhoto.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Currency(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Currency.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Document(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Document.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator DocumentType(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : DocumentType.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Education(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Education.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Exports(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Exports.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator ExternalLink(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : ExternalLink.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Faculty(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Faculty.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator FaveVideoEx(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : FaveVideoEx.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator FriendList(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : FriendList.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator FriendOnline(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : FriendOnline.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Geo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Geo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Gift(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Gift.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GiftItem(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GiftItem.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Graffiti(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Graffiti.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Group(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Group.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupCover(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupCover.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupCoverImage(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupCoverImage.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupInfo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupInfo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupMember(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupMember.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupsCatalogInfo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupsCatalogInfo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator GroupsEditParams(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : GroupsEditParams.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator History(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : History.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator HistoryAttachment(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : HistoryAttachment.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator InformationAboutOffers(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: InformationAboutOffers.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LastActivity(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : LastActivity.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LastSeen(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : LastSeen.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Likes(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Likes.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Link(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Link.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LinkButton(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : LinkButton.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LinkButtonAction(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : LinkButtonAction.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LongPollHistoryResponse(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: LongPollHistoryResponse.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LongPollServerResponse(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: LongPollServerResponse.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LookupContactsOther(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: LookupContactsOther.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator LookupContactsResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: LookupContactsResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Lyrics(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Lyrics.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Market(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Market.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MarketAlbum(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : MarketAlbum.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MarketCategory(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : MarketCategory.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MarketCategorySection(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: MarketCategorySection.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MarketComment(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : MarketComment.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Mention(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Mention.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Message(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Message.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MessagesGetObject(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : MessagesGetObject.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator MessagesPushSettings(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: MessagesPushSettings.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Military(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Military.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsBannedExList(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsBannedExList.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsBannedList(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsBannedList.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsItem(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsItem.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsSearchResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsSearchResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsSuggestions(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsSuggestions.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator NewsUserListItem(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : NewsUserListItem.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Note(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Note.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Occupation(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Occupation.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Page(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Page.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Photo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Photo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PhotoAlbum(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PhotoAlbum.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PhotoSize(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PhotoSize.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
	#pragma warning disable 618
		public static implicit operator PhotosList(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PhotosList.FromJson(response: response);
		}
	#pragma warning restore 618
		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Place(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Place.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Poll(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Poll.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PollAnswer(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PollAnswer.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PollAnswerVoters(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PollAnswerVoters.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Post(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Post.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PostReach(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PostReach.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PostSource(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PostSource.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PostSourceData(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PostSourceData.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PostView(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PostView.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Previews(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Previews.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Price(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Price.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator PushSettings(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : PushSettings.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Rating(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Rating.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Rect(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Rect.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Region(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Region.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Relative(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Relative.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator RepostResult(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : RepostResult.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Reposts(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Reposts.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator School(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : School.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator SchoolClass(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : SchoolClass.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator SearchDialogsResponse(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues
					? null
					: SearchDialogsResponse.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator StandInLife(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : StandInLife.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator StatsPeriod(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : StatsPeriod.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator StatsStruct(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : StatsStruct.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Status(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Status.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Sticker(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Sticker.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Store(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Store.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Street(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Street.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Tag(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Tag.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Tags(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Tags.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Topic(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Topic.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator University(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : University.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator UploadServerInfo(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : UploadServerInfo.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator User(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : User.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator UserOrGroup(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : UserOrGroup.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator Video(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : Video.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VideoAlbum(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : VideoAlbum.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VideoCatalog(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : VideoCatalog.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VideoCatalogItem(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : VideoCatalogItem.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VideoFiles(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : VideoFiles.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator VkObject(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : VkObject.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator WallGetObject(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : WallGetObject.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator WallReply(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : WallReply.FromJson(response: response);
		}

		/// <summary>
		/// Преобразовать из VkResponse
		/// </summary>
		/// <param name="response"> Ответ. </param>
		/// <returns>
		/// Результат преобразования.
		/// </returns>
		public static implicit operator AdsAccount(VkResponse response)
		{
			return response?._token == null || !response._token.HasValues ? null : AdsAccount.FromJson(response: response);
		}
	}
}