// Autogenerated at 03/28/2016 16:14:46
// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY
using VkNet.Enums.SafetyEnums;

namespace VkNet.Utils
{
	public partial class VkResponse
	{

		public static implicit operator AppFilter(VkResponse response)
		{
			return response == null ? null : AppFilter.FromJson(response);
		}

		public static implicit operator AppPlatforms(VkResponse response)
		{
			return response == null ? null : AppPlatforms.FromJson(response);
		}

		public static implicit operator AppRatingType(VkResponse response)
		{
			return response == null ? null : AppRatingType.FromJson(response);
		}

		public static implicit operator AppRequestType(VkResponse response)
		{
			return response == null ? null : AppRequestType.FromJson(response);
		}

		public static implicit operator AppSort(VkResponse response)
		{
			return response == null ? null : AppSort.FromJson(response);
		}

		public static implicit operator ChangeNameStatus(VkResponse response)
		{
			return response == null ? null : ChangeNameStatus.FromJson(response);
		}

		public static implicit operator CommentObjectType(VkResponse response)
		{
			return response == null ? null : CommentObjectType.FromJson(response);
		}

		public static implicit operator CommentsSort(VkResponse response)
		{
			return response == null ? null : CommentsSort.FromJson(response);
		}

		public static implicit operator Deactivated(VkResponse response)
		{
			return response == null ? null : Deactivated.FromJson(response);
		}

		public static implicit operator Display(VkResponse response)
		{
			return response == null ? null : Display.FromJson(response);
		}

		public static implicit operator FeedType(VkResponse response)
		{
			return response == null ? null : FeedType.FromJson(response);
		}

		public static implicit operator FriendsFilter(VkResponse response)
		{
			return response == null ? null : FriendsFilter.FromJson(response);
		}

		public static implicit operator FriendsOrder(VkResponse response)
		{
			return response == null ? null : FriendsOrder.FromJson(response);
		}

		public static implicit operator GroupsSort(VkResponse response)
		{
			return response == null ? null : GroupsSort.FromJson(response);
		}

		public static implicit operator GroupType(VkResponse response)
		{
			return response == null ? null : GroupType.FromJson(response);
		}

		public static implicit operator LikeObjectType(VkResponse response)
		{
			return response == null ? null : LikeObjectType.FromJson(response);
		}

		public static implicit operator LikesFilter(VkResponse response)
		{
			return response == null ? null : LikesFilter.FromJson(response);
		}

		public static implicit operator LinkAccessType(VkResponse response)
		{
			return response == null ? null : LinkAccessType.FromJson(response);
		}

		public static implicit operator MediaType(VkResponse response)
		{
			return response == null ? null : MediaType.FromJson(response);
		}

		public static implicit operator NameCase(VkResponse response)
		{
			return response == null ? null : NameCase.FromJson(response);
		}

		public static implicit operator NewsObjectTypes(VkResponse response)
		{
			return response == null ? null : NewsObjectTypes.FromJson(response);
		}

		public static implicit operator NewsTypes(VkResponse response)
		{
			return response == null ? null : NewsTypes.FromJson(response);
		}

		public static implicit operator OccupationType(VkResponse response)
		{
			return response == null ? null : OccupationType.FromJson(response);
		}

		public static implicit operator PhotoAlbumType(VkResponse response)
		{
			return response == null ? null : PhotoAlbumType.FromJson(response);
		}

		public static implicit operator PhotoFeedType(VkResponse response)
		{
			return response == null ? null : PhotoFeedType.FromJson(response);
		}

		public static implicit operator PhotoSearchRadius(VkResponse response)
		{
			return response == null ? null : PhotoSearchRadius.FromJson(response);
		}

		public static implicit operator PhotoSizeType(VkResponse response)
		{
			return response == null ? null : PhotoSizeType.FromJson(response);
		}

		public static implicit operator Platform(VkResponse response)
		{
			return response == null ? null : Platform.FromJson(response);
		}

		public static implicit operator PostSourceType(VkResponse response)
		{
			return response == null ? null : PostSourceType.FromJson(response);
		}

		public static implicit operator PostType(VkResponse response)
		{
			return response == null ? null : PostType.FromJson(response);
		}

		public static implicit operator PostTypeOrder(VkResponse response)
		{
			return response == null ? null : PostTypeOrder.FromJson(response);
		}

		public static implicit operator Privacy(VkResponse response)
		{
			return response == null ? null : Privacy.FromJson(response);
		}

		public static implicit operator RelativeType(VkResponse response)
		{
			return response == null ? null : RelativeType.FromJson(response);
		}

		public static implicit operator ReportType(VkResponse response)
		{
			return response == null ? null : ReportType.FromJson(response);
		}

		public static implicit operator Services(VkResponse response)
		{
			return response == null ? null : Services.FromJson(response);
		}

		public static implicit operator UserSection(VkResponse response)
		{
			return response == null ? null : UserSection.FromJson(response);
		}

		public static implicit operator VideoCatalogItemType(VkResponse response)
		{
			return response == null ? null : VideoCatalogItemType.FromJson(response);
		}

		public static implicit operator VideoCatalogType(VkResponse response)
		{
			return response == null ? null : VideoCatalogType.FromJson(response);
		}

		public static implicit operator WallFilter(VkResponse response)
		{
			return response == null ? null : WallFilter.FromJson(response);
		}
	}
}