using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace VkNet.SourceGenerator
{
	[Generator]
	public class VkResponseToSafetyEnumCastGenerator : VkResponseImplicitGeneratorBase<VkResponseToSafetyEnumCastReceiver>
	{
		/// <inheritdoc />
		protected override string GetSourceCode()
		{
			var sb = new StringBuilder();
			sb.AppendLine("// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY");
			sb.AppendLine();

			foreach (var usingName in Receiver.CandidateUsingList)
			{
				sb.AppendLine($"using {usingName};");
			}

			sb.AppendLine();
			sb.AppendLine("namespace VkNet.Utils");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic partial class VkResponse");
			sb.AppendLine("\t{");

			foreach (var s in Receiver.CandidateClasses.Distinct())
			{
				sb.AppendLine("\t\t/// <summary>");
				sb.AppendLine("\t\t/// Преобразовать из VkResponse");
				sb.AppendLine("\t\t/// </summary>");
				sb.AppendLine("\t\t/// <param name=\"response\"> Ответ. </param>");
				sb.AppendLine("\t\t/// <returns>");
				sb.AppendLine("\t\t/// Результат преобразования.");
				sb.AppendLine("\t\t/// </returns>");
				sb.AppendLine($"\t\tpublic static implicit operator {s}(VkResponse response)");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\treturn response == null ? null : {s}.FromJson(response);");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			return sb.ToString();
		}
	}
}