//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkNet.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkNet.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Заявка на добавление в друзья от данного пользователя одобрена.
		/// </summary>
		public static string AddFriendStatus_Accepted
		{
			get
			{
				return ResourceManager.GetString("AddFriendStatus_Accepted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Повторная отправка заявки.
		/// </summary>
		public static string AddFriendStatus_Resubmit
		{
			get
			{
				return ResourceManager.GetString("AddFriendStatus_Resubmit", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Заявка на добавление данного пользователя в друзья отправлена.
		/// </summary>
		public static string AddFriendStatus_Sended
		{
			get
			{
				return ResourceManager.GetString("AddFriendStatus_Sended", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Статус ответа неизвестен.
		/// </summary>
		public static string AddFriendStatus_Unknown
		{
			get
			{
				return ResourceManager.GetString("AddFriendStatus_Unknown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Помолвлен.
		/// </summary>
		public static string MaritalStatus_Engaged
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_Engaged", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Влюблён.
		/// </summary>
		public static string MaritalStatus_InLove
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_InLove", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Всё сложно.
		/// </summary>
		public static string MaritalStatus_ItsComplicated
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_ItsComplicated", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Женат.
		/// </summary>
		public static string MaritalStatus_Married
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_Married", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Встречается.
		/// </summary>
		public static string MaritalStatus_Meets
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_Meets", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Не женат.
		/// </summary>
		public static string MaritalStatus_Single
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_Single", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to В активном поиске.
		/// </summary>
		public static string MaritalStatus_TheActiveSearch
		{
			get
			{
				return ResourceManager.GetString("MaritalStatus_TheActiveSearch", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Женский.
		/// </summary>
		public static string Sex_Female
		{
			get
			{
				return ResourceManager.GetString("Sex_Female", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Мужской.
		/// </summary>
		public static string Sex_Male
		{
			get
			{
				return ResourceManager.GetString("Sex_Male", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Не указан.
		/// </summary>
		public static string Sex_Unknown
		{
			get
			{
				return ResourceManager.GetString("Sex_Unknown", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to По популярности.
		/// </summary>
		public static string UserSort_ByPopularity
		{
			get
			{
				return ResourceManager.GetString("UserSort_ByPopularity", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to По дате регистрации.
		/// </summary>
		public static string UserSort_ByRegDate
		{
			get
			{
				return ResourceManager.GetString("UserSort_ByRegDate", resourceCulture);
			}
		}
	}
}