// Autogenerated at 11/09/2016 19:57:10
// DO NOT EDIT THIS FILE CAUSE ALL CHANGES WILL BE DELETED AUTOMATICALLY
using VkNet.Model.RequestParams;
// ReSharper disable MissingAnnotation

namespace VkNet.Utils
{
	partial class VkParameters
	{
		/// <summary>
        /// Преобразование класса <see cref="AccountRegisterDeviceParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AccountRegisterDeviceParams p)
		{
            return AccountRegisterDeviceParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AccountSaveProfileInfoParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AccountSaveProfileInfoParams p)
		{
            return AccountSaveProfileInfoParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AppGetCatalogParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AppGetCatalogParams p)
		{
            return AppGetCatalogParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AppGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AppGetParams p)
		{
            return AppGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AppSendRequestParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AppSendRequestParams p)
		{
            return AppSendRequestParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AudioEditParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AudioEditParams p)
		{
            return AudioEditParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AudioGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AudioGetParams p)
		{
            return AudioGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AudioSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AudioSearchParams p)
		{
            return AudioSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AuthConfirmParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AuthConfirmParams p)
		{
            return AuthConfirmParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="AuthSignupParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(AuthSignupParams p)
		{
            return AuthSignupParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardAddTopicParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardAddTopicParams p)
		{
            return BoardAddTopicParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardCommentParams p)
		{
            return BoardCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardCreateCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardCreateCommentParams p)
		{
            return BoardCreateCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardEditCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardEditCommentParams p)
		{
            return BoardEditCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardEditTopicParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardEditTopicParams p)
		{
            return BoardEditTopicParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardGetCommentsParams p)
		{
            return BoardGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardGetTopicsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardGetTopicsParams p)
		{
            return BoardGetTopicsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="BoardTopicParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(BoardTopicParams p)
		{
            return BoardTopicParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="FriendsGetMutualParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(FriendsGetMutualParams p)
		{
            return FriendsGetMutualParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="FriendsGetOnlineParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(FriendsGetOnlineParams p)
		{
            return FriendsGetOnlineParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="FriendsGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(FriendsGetParams p)
		{
            return FriendsGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="FriendsGetRequestsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(FriendsGetRequestsParams p)
		{
            return FriendsGetRequestsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="FriendsSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(FriendsSearchParams p)
		{
            return FriendsSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsBanUserParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsBanUserParams p)
		{
            return GroupsBanUserParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsEditManagerParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsEditManagerParams p)
		{
            return GroupsEditManagerParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsEditParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsEditParams p)
		{
            return GroupsEditParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsGetMembersParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsGetMembersParams p)
		{
            return GroupsGetMembersParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsGetParams p)
		{
            return GroupsGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="GroupsSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(GroupsSearchParams p)
		{
            return GroupsSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="LikesAddParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(LikesAddParams p)
		{
            return LikesAddParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="LikesGetListParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(LikesGetListParams p)
		{
            return LikesGetListParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MarketCreateCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MarketCreateCommentParams p)
		{
            return MarketCreateCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MarketGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MarketGetCommentsParams p)
		{
            return MarketGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MarketProductParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MarketProductParams p)
		{
            return MarketProductParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MarketSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MarketSearchParams p)
		{
            return MarketSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesDialogsGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesDialogsGetParams p)
		{
            return MessagesDialogsGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesGetHistoryAttachmentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesGetHistoryAttachmentsParams p)
		{
            return MessagesGetHistoryAttachmentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesGetHistoryParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesGetHistoryParams p)
		{
            return MessagesGetHistoryParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesGetLongPollHistoryParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesGetLongPollHistoryParams p)
		{
            return MessagesGetLongPollHistoryParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesGetParams p)
		{
            return MessagesGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesSendParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesSendParams p)
		{
            return MessagesSendParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="MessagesSendStickerParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(MessagesSendStickerParams p)
		{
            return MessagesSendStickerParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="NewsFeedGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(NewsFeedGetCommentsParams p)
		{
            return NewsFeedGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="NewsFeedGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(NewsFeedGetParams p)
		{
            return NewsFeedGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="NewsFeedGetRecommendedParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(NewsFeedGetRecommendedParams p)
		{
            return NewsFeedGetRecommendedParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="NewsFeedSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(NewsFeedSearchParams p)
		{
            return NewsFeedSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PagesGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PagesGetParams p)
		{
            return PagesGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoCreateAlbumParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoCreateAlbumParams p)
		{
            return PhotoCreateAlbumParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoCreateCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoCreateCommentParams p)
		{
            return PhotoCreateCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoEditAlbumParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoEditAlbumParams p)
		{
            return PhotoEditAlbumParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoEditParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoEditParams p)
		{
            return PhotoEditParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetAlbumsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetAlbumsParams p)
		{
            return PhotoGetAlbumsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetAllCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetAllCommentsParams p)
		{
            return PhotoGetAllCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetAllParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetAllParams p)
		{
            return PhotoGetAllParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetCommentsParams p)
		{
            return PhotoGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetParams p)
		{
            return PhotoGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoGetUserPhotosParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoGetUserPhotosParams p)
		{
            return PhotoGetUserPhotosParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoPutTagParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoPutTagParams p)
		{
            return PhotoPutTagParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoSaveParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoSaveParams p)
		{
            return PhotoSaveParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="PhotoSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(PhotoSearchParams p)
		{
            return PhotoSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="UserSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(UserSearchParams p)
		{
            return UserSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="UsersGetNearbyParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(UsersGetNearbyParams p)
		{
            return UsersGetNearbyParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoCreateCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoCreateCommentParams p)
		{
            return VideoCreateCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoEditParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoEditParams p)
		{
            return VideoEditParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoGetCommentsParams p)
		{
            return VideoGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoGetParams p)
		{
            return VideoGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoReorderVideosParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoReorderVideosParams p)
		{
            return VideoReorderVideosParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoSaveParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoSaveParams p)
		{
            return VideoSaveParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="VideoSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(VideoSearchParams p)
		{
            return VideoSearchParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallAddCommentParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallAddCommentParams p)
		{
            return WallAddCommentParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallEditParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallEditParams p)
		{
            return WallEditParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallGetCommentsParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallGetCommentsParams p)
		{
            return WallGetCommentsParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallGetParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallGetParams p)
		{
            return WallGetParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallPostParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallPostParams p)
		{
            return WallPostParams.ToVkParameters(p);
        }

		/// <summary>
        /// Преобразование класса <see cref="WallSearchParams"/> в <see cref="VkParameters"/>.
        /// </summary>
        /// <param name="p">Параметр.</param>
        /// <returns>
        /// Результат преобразования.
        /// </returns> 
		public static implicit operator VkParameters(WallSearchParams p)
		{
            return WallSearchParams.ToVkParameters(p);
        }

	}
}